// <auto-generated />
using System;
using ApiCaller.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiCaller.Migrations
{
    [DbContext(typeof(ApiCallerContext))]
    [Migration("20190128200143_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiCaller.Models.Clients", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("NotificationMessageClients");
                });

            modelBuilder.Entity("ApiCaller.Models.Companies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("NotificationMessageCompanies");
                });

            modelBuilder.Entity("ApiCaller.Models.Identifiers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientID");

                    b.Property<Guid>("GUID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("NotificationMessageIdentifiers");
                });

            modelBuilder.Entity("ApiCaller.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bcc");

                    b.Property<string>("Body");

                    b.Property<string>("Cc");

                    b.Property<bool>("IsSent");

                    b.Property<string>("MailTo")
                        .IsRequired();

                    b.Property<string>("Subject");

                    b.Property<DateTime>("TriggerTime");

                    b.HasKey("ID");

                    b.ToTable("NotificationMessageHistory");
                });

            modelBuilder.Entity("ApiCaller.Models.MessageAttachment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Body");

                    b.Property<int>("MessageID");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.HasIndex("MessageID");

                    b.ToTable("NotificationMessageAttachmentHistory");
                });

            modelBuilder.Entity("ApiCaller.Models.Clients", b =>
                {
                    b.HasOne("ApiCaller.Models.Companies", "Companies")
                        .WithMany("Clients")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ApiCaller.Models.Identifiers", b =>
                {
                    b.HasOne("ApiCaller.Models.Clients", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ApiCaller.Models.MessageAttachment", b =>
                {
                    b.HasOne("ApiCaller.Models.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
